nombres=input("Cuales son sus nombres?: ")
apellidos=input("Cuales son sus apellidos?: ")
seccion=(input("Escriba el código sección: "))
sede=input("A que sede pertenece?: ")
print("Hola! "+nombres+" "+apellidos+" "+seccion+" "+sede+".")
